#!/bin/bash

if [ -f all_sources.txt ]; then
  rm all_sources.txt
fi

EXCLUDE_PATTERNS=(
  ".*\.abi.json"
  ".*\.icon"
  ".*\.ico"
  ".*\.avif"
  ".*\.png"
  ".*\.svg"
  "gluing-project-contents"
  "package-lock\.json"
  "yarn\.lock"
  "pnpm-lock.yaml"
  "all_sources.txt"
  "certs/"
)

EXCLUDE_PATTERN="(^|/)($(
  IFS="|"
  echo "${EXCLUDE_PATTERNS[*]}"
))$"

git ls-files | grep -vE "$EXCLUDE_PATTERN" | while read -r file; do
  {
    echo "// ===== $file ====="
    cat "$file"
    echo -e "\n"
  } >>all_sources.txt

done
